name: HackReport
main: xyz.acrylicstyle.hackReport.HackReport
version: 0.0.1
softdepend:
  - LuckPerms
depend:
  - TomeitoLib
commands:
  report:
    description: "Report a player."
  reports:
    description: "Shows reports list." # actually requires OP
    aliases: ["reportlist"]
  player:
    description: "Opens player action GUI." # actually requires OP
    aliases: ["playeraction"]
  hackreport:
    description: "HackReport root command."
    aliases: "hr"
  ignore:
    description: "Ignore players' chat"
  mute:
    description: "Mute a player."
  opchat:
    aliases: "oc"